language: node_js
node_js: stable
before_install:
- openssl aes-256-cbc -K $encrypted_ab176a35cf3c_key -iv $encrypted_ab176a35cf3c_iv
  -in id_rsa.enc -out ~/.ssh/id_rsa -d
- chmod 600 ~/.ssh/id_rsa
- echo -e "Host 95.179.186.54\n\tStrictHostKeyChecking no\n" >> ~/.ssh/config
- npm install
- npm run build
after_success:
- cd .vuepress/dist
- scp -o stricthostkeychecking=no -r ./* root@95.179.186.54:/www/blog
